ana_name: hbbhtt
var_name: DNN
era: 13TeV
mass: 125
ggHH_selection: mh
vbf_selection: mh
years:
    - 2016
    # - 2017
    # - 2018
channels:
    # - eTau
    # - muTau
    - tauTau
vbf_classes:
    - GGF
    - VBF
    - TT
    # - ttH
    - DY
ggHH_categories:
    - res1b
    - res2b
    - boosted
signals:
    - ggHH_kl_0_kt_1
    - ggHH_kl_1_kt_1
    - ggHH_kl_2p45_kt_1
    - ggHH_kl_5_kt_1
    - qqHH_CV_0p5_C2V_1_kl_1
    - qqHH_CV_1p5_C2V_1_kl_1
    - qqHH_CV_1_C2V_1_kl_0
    - qqHH_CV_1_C2V_1_kl_1
    - qqHH_CV_1_C2V_1_kl_2
    - qqHH_CV_1_C2V_2_kl_1
common_backgrounds:
    - TT
    - EWK
    - singleT
    - W
    - VV
    - VVV
    - TTX
    - QCD
    - DY_LM
singleH_bkg:
    - ZH
    - WH
    - ttH
    - ggH
    - VBFH
DY_bkg:
    - n_b_bins: 3
    - n_pt_bins: 6
