analysis: hh_bbtt
type: resonant
model:
  parameters: [ MX ]
  param_dependent_bkg: false
  input_file_pattern: ${ERA}.root
eras:
  - Run2_2018
channels:
  - eTau
  - muTau
  - tauTau
categories:
  - res1b
  - res2b
  - boosted
processes:
  - process: data_obs
    is_data: true
    is_asimov_data: true
  - process: GluGluToRadionToHHTo2B2Tau_M_${MX}
    hist_name: GluGluToRadionToHHTo2B2Tau_M-${MX}
    param_values: [ 250, 260, 270, 280, 300, 320, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900,
                    1000, 1250, 1500, 1750, 2000, 2500, 3000,  ]
    is_signal: true
    scale: 2 * 6.272E-02 * 5.824E-01
  - TT
  - DY
uncertainties:
  - name: lumi_13TeV
    type: lnN
    value: 0.03
    processes: ^.*$
  - name: JER
    type: auto
    categories: ^res[12]b$
autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001
autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1