analysis: hh_bbww
type: resonant
model:
  parameters: [ MX ]
  param_dependent_bkg: true
  input_file_pattern: dnn_M${MX}_Signal/dnn_M${MX}_Signal.root
hist_bins: [ 0, 0.3, 1 ]
signalFractionForRelevantBins: 0.2
eras:
  - Run3_2022
channels:
  - muMu
categories:
  - inclusive
processes:
  - process: data_obs
    is_data: true
    is_asimov_data: true
  - process: GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_${MX}
    hist_name: GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_${MX}
    param_values: [ 250, 260, 270, 280, 300, 350, 450, 550, 600, 650, 700, 800 ]
    is_signal: true
    scale: 2 * 5.824e-01 * ( 2.137e-01 * 3 * 10.86e-02 * 3 * 10.86e-02 + 2 * 2.619E-02 * 3 * 3.3658e-02 * 0.2)
  - TT
  - DY
  # - W
  # - Other
uncertainties:
  - name: lumi_13TeV
    type: lnN
    value: 0.014 # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3
  #- name: eleID
  #  type: auto
  - name: MuonID_TightID
    type: shape
  - name: MuonID_TightIDIso
    type: shape
  - name: CMS_pileup_2022
    type: shape
    eras:
    - Run3_2022
autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001
autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1
