analysis: hh_bbt
type: resonant
model:
  parameters: [ MX ]
  param_dependent_bkg: false
  input_file_pattern: ${ERA}.root
eras:
  - Run2_2018
  #- Run2_2017
  - Run2_2016
  #- Run2_2016_HIPM
channels:
  #- eTau
  #- muTau
  - tauTau
categories:
  - res1b
  - res2b
  - boosted
processes:
  - process: data_obs
    is_data: true
    is_asimov_data: true
  - process: GluGluToRadionToHHTo2B2Tau_M_${MX}
    hist_name: GluGluToRadionToHHTo2B2Tau_M-${MX}
    param_values: [ 250, 260, 270, 280, 300, 320, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900,
                    1000, 1250, 1500, 1750, 2000, 2500, 3000,  ]
    is_signal: true
    scale: 2 * 6.272E-02 * 5.824E-01
  - process: TT
    allowNegativeContributions: False
    #subprocesses:
  - process: DY
    allowNegativeContributions: False
  - process: VV
    allowNegativeContributions: True
    subprocesses:
    - WW
    - WZ
    - ZZ
  - process: ST
    allowNegativeContributions: True
    subprocesses:
    - ST_tW_antitop_5f_InclusiveDecays
    - ST_tW_top_5f_InclusiveDecays
    - ST_t-channel_antitop_4f_InclusiveDecays
    - ST_t-channel_top_4f_InclusiveDecays
  #- process: TW
  #  allowNegativeContributions: True
  - process: TTX
    allowNegativeContributions: True
    subprocesses:
    - TTWJetsToLNu
    - TTWJetsToQQ
    - TTWW
    - TTWZ
    - TTWH
    - TTZH
    - TTZToLLNuNu_M-10
    - TTZToQQ
    - TTZZ
    - TTZToNuNu
    - TTGamma_Dilept
    - TTGamma_Hadronic
    - TTGamma_SingleLept
    - TTGG
    - TTZZTo4b
    - TTZZToNon4b
    - TTZHTo4b
    - TTWH
    - TTZHTo4b
    - TTZHToNon4b
    - TTZH
    - TTTJ
    - TTTT
    - TTTW
    - TT4b
  - process: W
    allowNegativeContributions: False
    #subprocesses:
    #- WJetsToLNu
    #- W1JetsToLNu
    #- W2JetsToLNu
    #- W3JetsToLNu
    #- W4JetsToLNu
    #- WJetsToLNu_HT-70To100
    #- WJetsToLNu_HT-100To200
    #- WJetsToLNu_HT-1200To2500
    #- WJetsToLNu_HT-200To400
    #- WJetsToLNu_HT-2500ToInf
    #- WJetsToLNu_HT-400To600
    #- WJetsToLNu_HT-600To800
    #- WJetsToLNu_HT-800To1200
  - process: EWK
    allowNegativeContributions: True
    subprocesses:
    - EWK_WplusToLNu
    - EWK_WminusToLNu
    - EWK_ZTo2L
    - EWK_ZTo2Nu
  - process: VVV
    allowNegativeContributions: True
    subprocesses:
    - WWW_4F
    - WWZ_4F
    - WZZ
    - ZZZ
  - process: QCD
    allowNegativeContributions: True
  - process: ZJNuNu
    allowNegativeContributions: True
    #subprocesses:
    #- ZJetsToNuNu_HT-100To200
    #- ZJetsToNuNu_HT-1200To2500
    #- ZJetsToNuNu_HT-200To400
    #- ZJetsToNuNu_HT-2500ToInf
    #- ZJetsToNuNu_HT-400To600
    #- ZJetsToNuNu_HT-600To800
    #- ZJetsToNuNu_HT-800To1200
  - process: ggH_htt
    allowNegativeContributions: True
    subprocesses:
    - GluGluHToTauTau_M125
    isRelatedTo: VH
  - process: qqH_htt
    allowNegativeContributions: True
    subprocesses:
    - VBFHToTauTau_M125
    isRelatedTo: VH
  - process: HWW
    allowNegativeContributions: True
    subprocesses:
    - VBFHToWWTo2L2Nu_M125
    - HWplusJ_HToWW_M125
    - HWminusJ_HToWW_M125
    isRelatedTo: VH
  - process: VH
    allowNegativeContributions: True
    subprocesses:
    - ggHToZZTo2L2Q
    - HZJ_HToWW_M125
    - GluGluZH_HToWW_ZTo2L_M125
  - process: VH_htt
    allowNegativeContributions: True
    subprocesses:
    - WplusHToTauTau_M125
    - WminusHToTauTau_M125
    - ZHToTauTau_M125
    isRelatedTo: VH
  - process: ZH_hbb
    allowNegativeContributions: True
    subprocesses:
    - ZH_Hbb_Zll
    - ZH_Hbb_Zqq
    isRelatedTo: VH
  - process: ttH
    allowNegativeContributions: True
    subprocesses:
    - ttH
uncertainties:
  - name: lumi_13TeV
    type: lnN
    value: 0.03

autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001
autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1